
default: &DEFAULTS
  app: &APP_DEFAULTS
    scheme: GovUK-UIComponents
    workspace: GovUK-UIComponents.xcworkspace
    project: UIComponentsExample/GovUK-UIComponents.xcodeproj
    test_plan: UIComponents,GovKit
  scan:
    output_directory: test_output
    devices:
      - iPhone 16 Pro (18.6)

unit:
  <<: *DEFAULTS
