
default: &DEFAULTS
  app: &APP_DEFAULTS
    scheme: GovUK-UIComponents
    project: UIComponetsExample/GovUK-UIComponents.xcodeproj
    test_plan: GovUK-UIComponents
  scan:
    output_directory: test_output
    devices:
      - iPhone 16 Pro (18.6)

unit:
  <<: *DEFAULTS
