
default: &DEFAULTS
  app: &APP_DEFAULTS
    scheme: GovKitUIExample
    project: GovKitUIExample/GovKitUI.xcodeproj
    test_plan: GovKitUI
  scan:
    output_directory: test_output
    devices:
      - iPhone 16 Pro (18.6)

unit:
  <<: *DEFAULTS
