
default: &DEFAULTS
  app: &APP_DEFAULTS
    scheme: GovKitExample
    project: GovKitExample/GovKitExample.xcodeproj
    test_plan: GovKitExample
  scan:
    output_directory: test_output
    devices:
      - iPhone 16 Pro (18.6)

unit:
  <<: *DEFAULTS
