
default: &DEFAULTS
  app: &APP_DEFAULTS
    workspace: UIComponents/GovUK-UIComponents.xcworkspace
    project: UIComponentsExample/GovUK-UIComponents.xcodeproj
    test_plan: GovKit,UIComponents
  scan:
    output_directory: test_output
    devices:
      - iPhone 16 Pro (18.6)

unit:
  <<: *DEFAULTS
